import { useState, useMemo, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'

const FLASHCARD_SESSION_KEY = 'flashcardSession'
const PRACTICE_SESSION_KEY = 'practiceTestSession'
import { useAuth } from '../contexts/AuthContext'
import AppHeader from '../components/AppHeader'
import TraineeNavTabs from '../components/TraineeNavTabs'
import CertificationProgress from '../components/CertificationProgress'
import TrainingHealth from '../components/TrainingHealth'
import TraineeShiftCard from '../components/TraineeShiftCard'
import ShiftDetailView from '../components/ShiftDetailView'
import TrainerRatingModal from '../components/TrainerRatingModal'
import VerbalCertChecklistModal from '../components/VerbalCertChecklistModal'
import { useTrainingData } from '../hooks/useTrainingData'
import { useStaffAccounts } from '../hooks/useStaffAccounts'
import { useTestAttempts } from '../hooks/useTestAttempts'
import { useFlashcardMastery } from '../hooks/useFlashcardMastery'
import { getCoachTip } from '../services/ai'
import { REQUIRED_SHIFT_KEYS, SHIFT_META } from '../constants'
import { TESTS } from '../data/quizDatabase'
import { FLASHCARD_SETS } from '../data/flashcardDatabase'
import {
  getCertificationProgress,
  getTrainingHealth,
  getNextShift,
  formatWhenHuman,
  isShiftComplete,
  getShiftRequiredTestIds,
} from '../utils/helpers'
import SkeletonCards from '../components/SkeletonCard'

const SHIFT_ORDER = ['follow', 'rev1', 'rev2', 'rev3', 'rev4', 'foodrun', 'cert']

export default function TraineeDashboard() {
  const navigate = useNavigate()
  const { currentUser } = useAuth()
  const traineeId = currentUser?.traineeId || currentUser?.id
  const { trainingData, setTrainingData, saveTrainingData, trainingDataLoading } = useTrainingData()
  const { staffAccounts } = useStaffAccounts()
  const { getBestScore, isTestPassed } = useTestAttempts(traineeId)

  const [detailShiftKey, setDetailShiftKey] = useState(null)
  const [ratingModal, setRatingModal] = useState({ open: false, shiftKey: null })
  const [showCompletedOpen, setShowCompletedOpen] = useState(false)
  const [coachTip, setCoachTip] = useState('')
  const [coachTipLoading, setCoachTipLoading] = useState(false)
  const [verbalChecklistOpen, setVerbalChecklistOpen] = useState(false)

  const { getStruggleCards } = useFlashcardMastery(traineeId)
  const struggleSetTitles = useMemo(() => {
    return FLASHCARD_SETS.filter((s) => getStruggleCards(s.id).length > 0).map((s) => s.title)
  }, [getStruggleCards])

  const rawRec = (traineeId && trainingData?.[traineeId]) || null
  const rec = rawRec ? { ...rawRec, id: rawRec.id || traineeId } : null
  const nextShift = rec ? getNextShift(rec, staffAccounts, SHIFT_ORDER) : null
  const progress = rec ? getCertificationProgress(rec) : { done: 0, total: 6, pct: 0 }
  const baseHealth = rec ? getTrainingHealth(rec) : { shifts: '0/6', quizAvg: 0, passRate: 0, needPractice: 0 }
  const health = useMemo(() => {
    const officialTests = (TESTS || []).filter((t) => t.id !== 'bonus_test')
    const needPractice = struggleSetTitles.length
    if (officialTests.length === 0) return { ...baseHealth, needPractice }
    const scores = officialTests.map((t) => getBestScore(t.id)).filter((s) => s > 0)
    const passed = officialTests.filter((t) => isTestPassed(t.id)).length
    const quizAvg = scores.length ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : baseHealth.quizAvg
    const passRate = officialTests.length ? Math.round((passed / officialTests.length) * 100) : baseHealth.passRate
    return { ...baseHealth, quizAvg, passRate, needPractice }
  }, [baseHealth, getBestScore, isTestPassed, struggleSetTitles.length])

  const incompleteShifts = SHIFT_ORDER.filter((key) => rec?.schedule?.[key] && !isShiftComplete(rec, key))
  const completedShifts = REQUIRED_SHIFT_KEYS.filter((key) => rec && isShiftComplete(rec, key))
  const shiftsRatable = SHIFT_ORDER.filter((key) => rec?.schedule?.[key]?.trainerSignedAt && rec?.schedule?.[key]?.trainer)
  const trainerRatings = rec?.trainerRatings || {}

  const resumeFlashcard = useMemo(() => {
    if (!traineeId) return null
    try {
      const raw = localStorage.getItem(`${FLASHCARD_SESSION_KEY}_${traineeId}`)
      if (!raw) return null
      const s = JSON.parse(raw)
      if (s?.setId) return { setId: s.setId, focusMode: !!s.focusMode, index: s.index ?? 0 }
    } catch (_) {}
    return null
  }, [traineeId])

  const resumePracticeTest = useMemo(() => {
    if (!traineeId) return null
    try {
      const raw = localStorage.getItem(`${PRACTICE_SESSION_KEY}_${traineeId}`)
      if (!raw) return null
      const s = JSON.parse(raw)
      if (s?.testId && s?.mode === 'practice') return { testId: s.testId }
    } catch (_) {}
    return null
  }, [traineeId])

  const autoGenerated = useRef(false)
  useEffect(() => {
    if (!rec || !traineeId || autoGenerated.current) return
    autoGenerated.current = true
    const summary = `Certification: ${progress.done}/${progress.total} shifts. Quiz avg: ${health.quizAvg}%. Pass rate: ${health.passRate}%. Need practice: ${struggleSetTitles.length} topic(s): ${struggleSetTitles.join(', ') || 'none'}.`
    getCoachTip(summary)
      .then(setCoachTip)
      .catch(() => setCoachTip(''))
  }, [traineeId, rec, struggleSetTitles, progress.done, progress.total, health.quizAvg, health.passRate])

  const handleSaveRating = (shiftKey, payload) => {
    if (!traineeId || !rec) return
    const next = { ...trainingData }
    if (!next[traineeId]) next[traineeId] = { ...rec }
    if (!next[traineeId].trainerRatings) next[traineeId].trainerRatings = {}
    next[traineeId].trainerRatings[shiftKey] = payload
    setTrainingData(next)
    saveTrainingData(next)
    setRatingModal({ open: false, shiftKey: null })
  }

  if (!traineeId) {
    return (
      <>
        <AppHeader />
        <div className="container mx-auto max-w-4xl p-4">
          <p className="text-gray-600">You are not logged in as a trainee. Use your employee number to sign in.</p>
        </div>
      </>
    )
  }

  if (!rec) {
    return (
      <>
        <AppHeader />
        <div className="container mx-auto max-w-4xl p-4">
          <div className="content-area rounded-xl border border-gray-200 bg-gray-50 p-6 text-center">
            <p className="text-gray-600 mb-2">No training record found.</p>
            <p className="text-sm text-gray-500">Ask your manager to add you as a trainee from the Manager dashboard.</p>
          </div>
        </div>
      </>
    )
  }

  if (detailShiftKey) {
    return (
      <>
        <AppHeader />
        <div className="container mx-auto max-w-4xl p-4">
          <ShiftDetailView
            shiftKey={detailShiftKey}
            rec={rec}
            traineeId={traineeId}
            staffAccounts={staffAccounts}
            onBack={() => setDetailShiftKey(null)}
          />
        </div>
      </>
    )
  }

  const nextMeta = nextShift && SHIFT_META[nextShift.key]
  const nextWhenStr = nextShift?.when ? formatWhenHuman(nextShift.when) : '—'

  return (
    <>
      <AppHeader />
      <div className="container mx-auto max-w-4xl px-4 pb-8">
        <TraineeNavTabs />
        <div className="content-area">
          {trainingDataLoading ? (
            <>
              <div className="mb-2 h-7 w-48 rounded bg-gray-200 animate-pulse" aria-hidden />
              <div className="mb-6 h-4 w-64 rounded bg-gray-100 animate-pulse" aria-hidden />
              <SkeletonCards count={4} />
            </>
          ) : (
            <>
          <h2 className="mb-2 text-xl font-bold text-gray-800">Trainee Dashboard</h2>
          <p className="mb-6 text-sm text-gray-600">{rec?.store || currentUser?.store || 'Westfield'} · #{rec?.employeeNumber || currentUser?.empNum || '—'}</p>

          {/* What's Next - sticky so it stays visible when scrolling */}
          <section className="sticky top-0 z-10 mb-6 rounded-xl border-2 border-[var(--color-primary)] bg-green-50/50 p-4 shadow-sm backdrop-blur-sm">
            <h3 className="mb-2 text-sm font-bold uppercase tracking-wide text-[var(--color-primary)]">What&apos;s next</h3>
            {nextShift ? (
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div>
                  <div className="font-bold text-gray-800">
                    {nextMeta?.icon ? <span className="mr-1.5">{nextMeta?.icon}</span> : null}
                    {nextShift.label}
                  </div>
                  <div className="mt-1 text-sm text-gray-600">{nextWhenStr}</div>
                  <div className="mt-0.5 text-sm text-gray-500">Trainer: {nextShift.trainerName}</div>
                  <div className="mt-2 flex flex-wrap gap-2">
                    <button
                      type="button"
                      className="btn btn-small text-sm bg-[#5e35b1] border-[#5e35b1] text-white hover:bg-[#7e45c1] hover:border-[#7e45c1]"
                      onClick={() => navigate('/flashcards?set=verbal_cert')}
                    >
                      Study for Certification
                    </button>
                    {nextMeta?.flashcardSetId && (
                      <button
                        type="button"
                        className="btn btn-small text-sm"
                        onClick={() => navigate(`/flashcards?set=${encodeURIComponent(nextMeta.flashcardSetId)}`)}
                      >
                        Flashcards
                      </button>
                    )}
                    {shiftsRatable.includes(nextShift.key) && (
                      <button
                        type="button"
                        className="btn btn-small text-sm bg-[#e65100] border-[#e65100] text-white hover:bg-[#f57c00] hover:border-[#f57c00]"
                        onClick={() => setRatingModal({ open: true, shiftKey: nextShift.key })}
                      >
                        Rate your trainer
                      </button>
                    )}
                    <button
                      type="button"
                      className="btn btn-small text-sm"
                      onClick={() => {
                        const testIds = getShiftRequiredTestIds(nextShift.key, traineeId)
                        const first = testIds[0]
                        navigate(first ? `/quizzes?test=${encodeURIComponent(first)}&mode=practice` : '/quizzes')
                      }}
                    >
                      Practice Test
                    </button>
                    <button
                      type="button"
                      className="btn btn-small text-sm"
                      onClick={() => {
                        const testIds = getShiftRequiredTestIds(nextShift.key, traineeId)
                        const first = testIds[0]
                        navigate(first ? `/quizzes?test=${encodeURIComponent(first)}&mode=official` : '/quizzes#tests')
                      }}
                    >
                      Test
                    </button>
                  </div>
                </div>
                <span className="rounded-full bg-[#e65100] px-3 py-1 text-xs font-bold text-white">
                  {nextShift.complete ? 'Complete' : 'In progress'}
                </span>
              </div>
            ) : (
              <p className="text-gray-600">No upcoming shifts. All required shifts are complete or not yet scheduled.</p>
            )}
          </section>

          {/* Coach's Corner */}
          <section className="mb-6 rounded-xl border border-blue-200 bg-blue-50/50 p-4">
            <h3 className="mb-2 text-sm font-bold uppercase tracking-wide text-blue-800">Coach&apos;s corner</h3>
            <p className="mb-3 rounded-lg border-l-4 border-[var(--color-primary)] bg-white/80 px-3 py-2 text-sm text-gray-700">
              {struggleSetTitles.length > 0
                ? <>You have <strong>{struggleSetTitles.length}</strong> topic{struggleSetTitles.length !== 1 ? 's' : ''} with cards marked Need Practice. They show up first in Flashcards and in Focus mode.</>
                : 'No cards marked Need Practice yet. When you tap "Need Practice" or "Got it" on a flashcard, your choice is saved and used for quizzes and your study plan.'}
            </p>
            {coachTip ? (
              <div className="text-gray-800 whitespace-pre-wrap">{coachTip}</div>
            ) : (
              <p className="text-gray-600 text-sm">Get a personalized tip based on your progress.</p>
            )}
            <button
              type="button"
              className="btn btn-small mt-2"
              disabled={coachTipLoading}
              onClick={async () => {
                setCoachTipLoading(true)
                try {
                  const summary = `Certification: ${progress.done}/${progress.total} shifts. Quiz avg: ${health.quizAvg}%. Pass rate: ${health.passRate}%. Need practice: ${struggleSetTitles.length} topic(s): ${struggleSetTitles.join(', ') || 'none'}.`
                  const text = await getCoachTip(summary)
                  setCoachTip(text)
                } catch (_) {
                  setCoachTip('Could not load tip. Try again.')
                } finally {
                  setCoachTipLoading(false)
                }
              }}
            >
              {coachTipLoading ? 'Loading…' : coachTip ? 'Refresh tip' : 'Get coach tip'}
            </button>
          </section>

          {/* Resume last activity - only when there is a resumable session */}
          {(resumeFlashcard || resumePracticeTest) && (
            <section className="mb-6 rounded-xl border border-dashed border-gray-300 bg-gray-50/80 p-4">
              <h3 className="mb-2 text-xs font-bold uppercase tracking-wide text-gray-500">Resume last activity</h3>
              <div className="flex flex-wrap gap-3 items-center">
                {resumeFlashcard && (
                  <button
                    type="button"
                    className="btn btn-small"
                    onClick={() =>
                      navigate(`/flashcards?set=${encodeURIComponent(resumeFlashcard.setId)}${resumeFlashcard.focusMode ? '&focus=1' : ''}`, {
                        state: { resumeIndex: resumeFlashcard.index },
                      })
                    }
                  >
                    Resume flashcards
                  </button>
                )}
                {resumePracticeTest && (
                  <button
                    type="button"
                    className="btn btn-small"
                    onClick={() => navigate(`/quizzes?test=${encodeURIComponent(resumePracticeTest.testId)}&mode=practice`)}
                  >
                    Resume practice test
                  </button>
                )}
              </div>
            </section>
          )}

          {/* Certification: flashcard deck (legacy: Study for Certification) */}
          <section className="mb-6 rounded-xl border-2 border-[var(--color-primary)] bg-green-50/50 p-4">
            <h3 className="mb-2 text-sm font-bold uppercase tracking-wide text-[var(--color-primary)]">Certification</h3>
            <p className="mb-3 text-sm text-gray-600">Study the certification flashcard deck to prepare for your verbal certification.</p>
            <div className="flex flex-wrap gap-3 items-center">
              <button
                type="button"
                className="btn bg-[var(--color-primary)] text-white hover:opacity-90"
                onClick={() => navigate('/flashcards?set=verbal_cert')}
              >
                Study for Certification (flashcards)
              </button>
              <button
                type="button"
                className="btn btn-small btn-secondary"
                onClick={() => setVerbalChecklistOpen(true)}
              >
                Certification checklist
              </button>
            </div>
            <div className="mt-3">
              <CertificationProgress done={progress.done} total={progress.total} />
            </div>
          </section>

          {/* Study: Flashcards, Practice Tests, Tests */}
          <section className="mb-6">
            <h3 className="mb-2 border-l-4 border-l-[var(--color-primary)] pl-3 text-sm font-bold uppercase tracking-wide text-gray-500">Study & practice</h3>
            <div className="flex flex-wrap gap-3 items-center">
              <button type="button" className="btn" onClick={() => navigate('/flashcards')}>
                Flashcards
              </button>
              <button type="button" className="btn" onClick={() => navigate('/quizzes')}>
                Practice Tests
              </button>
              <button type="button" className="btn" onClick={() => navigate('/quizzes#tests')}>
                Tests
              </button>
            </div>
          </section>

          {/* Training health */}
          <section className="mb-6">
            <h3 className="mb-2 border-l-4 border-l-[var(--color-primary)] pl-3 text-sm font-bold uppercase tracking-wide text-gray-500">Training health</h3>
            <TrainingHealth
              shifts={health.shifts}
              quizAvg={health.quizAvg}
              passRate={health.passRate}
              needPractice={health.needPractice}
            />
          </section>

          {/* Schedule list (incomplete) */}
          <section className="mb-6" id="traineeScheduleSection">
            <h3 className="mb-3 border-l-4 border-l-[var(--color-primary)] pl-3 text-sm font-bold uppercase tracking-wide text-gray-500">Your schedule</h3>
            <div className="space-y-3">
              {incompleteShifts.length === 0 ? (
                <p className="text-gray-500">No incomplete shifts, or schedule not set yet.</p>
              ) : (
                incompleteShifts.map((key) => (
                  <TraineeShiftCard
                    key={key}
                    shiftKey={key}
                    rec={rec}
                    staffAccounts={staffAccounts}
                    onViewDetail={setDetailShiftKey}
                    onStudyFlashcards={(setId) => setId && navigate(`/flashcards?set=${encodeURIComponent(setId)}`)}
                    onPracticeTest={(shiftKey) => {
                      const ids = getShiftRequiredTestIds(shiftKey, traineeId)
                      if (ids[0]) navigate(`/quizzes?test=${encodeURIComponent(ids[0])}&mode=practice`)
                      else navigate('/quizzes')
                    }}
                    onTest={(shiftKey) => {
                      const ids = getShiftRequiredTestIds(shiftKey, traineeId)
                      if (ids[0]) navigate(`/quizzes?test=${encodeURIComponent(ids[0])}&mode=official`)
                      else navigate('/quizzes#tests')
                    }}
                  />
                ))
              )}
            </div>
          </section>

          {/* Shifts ready to rate (trainer has signed; rate before or after manager sign-off) */}
          {shiftsRatable.length > 0 && (
            <section className="mb-6">
              <h3 className="mb-3 border-l-4 border-l-amber-500 pl-3 text-sm font-bold uppercase tracking-wide text-gray-500">
                Rate your trainer
              </h3>
              <p className="mb-2 text-sm text-gray-600">Your trainer has signed off. Rate them to help us improve training.</p>
              <div className="space-y-2">
                {shiftsRatable.map((key) => {
                  const meta = SHIFT_META[key] || { label: key, icon: '' }
                  const item = rec.schedule?.[key] || {}
                  const whenStr = item.when ? formatWhenHuman(item.when) : '—'
                  const trainerName = item.trainer
                    ? (staffAccounts[item.trainer]?.name || `#${item.trainer}`)
                    : '—'
                  const rated = !!trainerRatings[key]
                  return (
                    <div
                      key={key}
                      className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-amber-200 bg-amber-50/30 p-3"
                    >
                      <div>
                        <span className="font-medium text-gray-800">{meta.icon ? `${meta.icon} ` : ''}{meta.label}</span>
                        <div className="text-sm text-gray-500">{whenStr} · {trainerName}</div>
                      </div>
                      <button
                        type="button"
                        className="btn btn-small"
                        onClick={() =>
                          setRatingModal({
                            open: true,
                            shiftKey: key,
                          })
                        }
                      >
                        {rated ? 'Update rating' : 'Rate your trainer'}
                      </button>
                    </div>
                  )
                })}
              </div>
            </section>
          )}

          {/* Completed shifts (collapsed by default) */}
          <section>
            <button
              type="button"
              className="flex w-full items-center justify-between rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-left font-semibold text-gray-800"
              onClick={() => setShowCompletedOpen(!showCompletedOpen)}
            >
              <span>Completed shifts ({completedShifts.length})</span>
              <span className="text-gray-500">{showCompletedOpen ? '▴' : '▾'}</span>
            </button>
            {showCompletedOpen && (
              <div className="mt-2 space-y-2 rounded-b-xl border border-t-0 border-gray-200 bg-green-50/30 p-4">
                {completedShifts.length === 0 ? (
                  <p className="text-sm text-gray-500">None yet. Complete shifts (trainer + manager sign-off) to see them here.</p>
                ) : (
                  completedShifts.map((key) => {
                    const meta = SHIFT_META[key] || { label: key, icon: '' }
                    const item = rec.schedule?.[key] || {}
                    const whenStr = item.when ? formatWhenHuman(item.when) : '—'
                    const trainerName = item.trainer
                      ? (staffAccounts[item.trainer]?.name || `#${item.trainer}`)
                      : '—'
                    const rated = !!trainerRatings[key]
                    return (
                      <div
                        key={key}
                        className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-green-200 bg-white p-3"
                      >
                        <div>
                          <span className="font-medium text-gray-800">{meta.icon ? `${meta.icon} ` : ''}{meta.label}</span>
                          <div className="text-sm text-gray-500">{whenStr} · {trainerName}</div>
                        </div>
                        <button
                          type="button"
                          className="btn btn-small"
                          onClick={() =>
                            setRatingModal({
                              open: true,
                              shiftKey: key,
                            })
                          }
                        >
                          {rated ? 'Update rating' : 'Rate your trainer'}
                        </button>
                      </div>
                    )
                  })
                )}
              </div>
            )}
          </section>
            </>
          )}
        </div>
      </div>

      {/* Trainer rating modal */}
      <VerbalCertChecklistModal open={verbalChecklistOpen} onClose={() => setVerbalChecklistOpen(false)} />

      {ratingModal.open && ratingModal.shiftKey && (
        <TrainerRatingModal
          open
          traineeId={traineeId}
          shiftKey={ratingModal.shiftKey}
          shiftLabel={(SHIFT_META[ratingModal.shiftKey] || {}).label || ratingModal.shiftKey}
          trainerId={rec.schedule?.[ratingModal.shiftKey]?.trainer}
          trainerName={
            rec.schedule?.[ratingModal.shiftKey]?.trainer
              ? (staffAccounts[rec.schedule[ratingModal.shiftKey].trainer]?.name ||
                `#${rec.schedule[ratingModal.shiftKey].trainer}`)
              : ''
          }
          existingRating={trainerRatings[ratingModal.shiftKey]}
          onSave={(payload) => handleSaveRating(ratingModal.shiftKey, payload)}
          onClose={() => setRatingModal({ open: false, shiftKey: null })}
        />
      )}
    </>
  )
}
